services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: internprojects-web
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production

      # These values are overridden by docker-compose.override.yml
      ConnectionStrings__DefaultConnection: ""
      ConnectionStrings__AppDbContext: ""

    networks:
      - internprojects-network


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: internprojects-sqlserver

    ports:
      - "1433:1433"

    volumes:
      # Keeps your database data after container restart
      - sqlserver_data:/var/opt/mssql

      # Folder containing your .bak database backup
      - ./backup:/var/opt/mssql/backup

    networks:
      - internprojects-network

    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -C -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 10


volumes:
  sqlserver_data:


networks:
  internprojects-network:
    driver: bridge
