services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: internprojects-web

    ports:
      - "8070:8080"

    depends_on:
      sqlserver:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=InternProjectsDB;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true"

    networks:
      - internprojects-network


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest

    container_name: internprojects-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -C -Q 'SELECT 1'"
        ]
      interval: 10s
      timeout: 5s
      retries: 20

    networks:
      - internprojects-network


volumes:
  sqlserver_data:


networks:
  internprojects-network:
    driver: bridge
